"""v0_update_student_table

Revision ID: 7c64f216e0a3
Revises: ddb1d941756f
Create Date: 2025-09-05 19:26:29.907412

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7c64f216e0a3'
down_revision: Union[str, Sequence[str], None] = 'ddb1d941756f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('first_name', sa.String(), nullable=False))
    op.add_column('student', sa.Column('last_name', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'student', ['id'])
    op.drop_column('student', 'name')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('student', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'student', type_='unique')
    op.drop_column('student', 'last_name')
    op.drop_column('student', 'first_name')
    # ### end Alembic commands ###
